### PR TITLE
buttonBarView

### PR DESCRIPTION
**Pull request by codwam**
BaseButtonBarPagerTabStripViewController.swift:
buttonBarView in code crash

### CODE REVIEW

**Comment by gonghao** [comment]
It's very useful! Hope to merge into master! 👍

**Comment by gonghao** [comment]
@santiagofm Maybe we should make a discussion about `IndicatorInfo` in #378

**Comment by codwam** [comment]
@santiagofm 
`1.`
The weak properties you can modify, it's easy.
`2.`
The `IndicatorInfo` extension some properties is needed.
Firstly: The Youtube example is simple, and my cell has more than three labels !!!
Seondly: extenstion `IndicatorInfo` then use runtime to extension is no effect, case it's `struct` !!!

**Comment by santiagofm** [comment]
@gonghao Sure

@codwam Yes, i understand. Still, i think it would be better to have this PR fix the weak `buttonBarView` issue so we merge it immediately and discuss what to do with `IndicatorInfo` in #378.

**Comment by codwam** [comment]
I'm not familiar with Pull Request，what should I do？

**Comment by santiagofm** [comment]
@codwam I think squashing those 4 commits into just one and then amending it to remove the `IndicatorInfo` stuff you should be good to go

**Comment by codwam** [comment]
Sorry, I don't know how to revert.

**Pull request closed without merging**
