### PR TITLE
Add BlackTranslucent example for Nav Button and Add Delegate method notification for real DidScrollEnd

### PR DESCRIPTION
**Pull request by xhzengAIB**

### CODE REVIEW

**Comment by xhzengAIB** [comment]
Hey @michaelEllisUy 

I'm very glad to receive your reply, when I click on the Nav Button, TableView Layout errors. 
Would you please tell me why?

Jack

**Comment by xhzengAIB** [comment]
Call [self moveToViewControllerAtIndex:xx]

**Comment by xhzengAIB** [comment]
fix the move methods bug

**Comment by mtnbarreto** [comment]
I think this can be fixed by setting up `automaticallyAdjustsScrollViewInsets` property to `false`.

**Pull request closed without merging**
