### PR TITLE
Implemented 'pagerTabStripViewController:didMoveToIndex:' delegate method

### LINKED ISSUE #38: New Feature: Delegate methods for 'willMoveToViewController: atIndex:

### PR DESCRIPTION
**Pull request by AnthonyMDev**
This should close #38 

**EDIT: `willMoveToIndex:` has since been added.
This has been tested thoroughly and works as expected on all view controllers.**

I've realized that there really is no good way to implement a 'willMoveToIndex:' delegate method, because the scroll view will already have moved half-way to the other view controller in the case of the user dragging the scroll view.

This method is called after the scroll view has completed all scrolling animations to reach the new view controller.

### CODE REVIEW

**Comment by AnthonyMDev** [comment]
Any chance that this PR will get accepted? If not, I need to fork the repository so that I can use it for my personal project.

Thanks

**Comment by AnthonyMDev** [comment]
@michaelEllisUy I've fixed the merge conflicts on this PR. Hoping to see this implemented soon?

**Comment by AnthonyMDev** [comment]
Just realized I've been tagging the wrong person when asking about the PR. Apparently @mtnbarreto is the author for this. Sorry.
@mtnbarreto do you think this will be implemented?

**Comment by AnthonyMDev** [comment]
This PR has been brought up to date with `master`.
I've also added a `willMoveToIndex:` delegate method that works perfectly.

@mtnbarreto Any chance that I can get a response on this PR? I'm using this in a production application right now and have to create my own private version of the Pod is a drag.

Thanks

**Comment by AnthonyMDev** [comment]
I see that there have been a bunch of changes that have caused merge conflicts for this PR. I'd be happy to resolve the merge conflicts if you are interested in pulling this in still? Otherwise, feel free to let me know and close the request.

**Comment by fedejordanolx** [comment]
I think this can be very useful

**Comment by kajensen** [comment]
How is this not part of this library?

**Comment by mtnbarreto** [comment]
@AnthonyMDev thanks for contributing but the base code has changed too much to merge these changes. In addition to that i don't want to make the library more complex to use.

**Pull request closed without merging**
