### PR TITLE
Fix crash when numberOfItemsInSection is 0.

### PR DESCRIPTION
**Pull request by antrix1989**

### CODE REVIEW

**Comment by michaelEllisUy** [comment]
Hey Sergey, 
 XLPagerTabStrip wasn't initially thought to handle an empty pager tab. In that case, we thought it would be handled by the app.

We can add an exception, so the app lets you know that it's crashing because of that.

What would be the case where you find this useful?

**Comment by antrix1989** [comment]
Hi Michael,
Thanks for the this cool component! You are doing great job!

In my mind you should handle an empty state. When I use this component, I assume it should behave like UITableView or UICollectionView. In my case, I do not know how many tabs I will have, so I do request to server, receive list of tabs, and then reload it again. It would be very annoying to check if itemsCount == 0, remove component, and if itemsCount > 0 add it.

**Comment by mtnbarreto** [comment]
@antrix1989 Thanks for the contribution but the library is not intended to be used with no pages. As a workaround you can show a empty state page showing only one childViewController. Alternatively you can hide tabbarstrip views if there is no pages to show.

**Comment by fotiDim** [comment]
@mtnbarreto how do you suggest to hide it? If I hide `ButtonBarView` though storyboard (default value is hidden) I still have the same problem.

**Pull request closed without merging**
