### PR TITLE
Remove two useless lines causing segmentation fault

### LINKED ISSUE #568: Segmentation fault: 11 after upgrade to XCode 9.3
XLPagerTabStrip-Version: 8.0.1

XCode 9.3
iOS 11.3

cocoapods: 1.5.0

----
Command failed due to signal: Segmentation fault: 11

While emitting IR SIL function "@_T015XLPagerTabStrip012TwitterPagerbC14ViewControllerC12observeValueySSSg10forKeyPath_ypSg2ofs10DictionaryVySC05NSKeyi6ChangeK0VypGSg6changeSvSg7contexttF".
 for 'observeValue(forKeyPath:of:change:context:)' at /Users/randy_kittinger/Documents/Projekte/joyclub-ios/Pods/XLPagerTabStrip/Sources/TwitterPagerTabStripViewController.swift:113:19

### PR DESCRIPTION
**Pull request by ochococo**
This PR fixes #568

### CODE REVIEW

**Comment by ochococo** [comment]
@mtnbarreto 👀

**Comment by MortMerr** [comment]
So...?

**Comment by StainlessStlRat** [comment]
Why arent these closed? The number of pull requests makes me hesitant to use the library

**Comment by ochococo** [comment]
OK, bye

**Pull request closed without merging**
